### PR TITLE
update Flux tutorial

### PR DESCRIPTION
**Pull request by ryanday36**
Updates some paragraphs to reflect the fact that Flux is now running as the system scheduler on some LC clusters. Also adds information about some commands and flags that I didn't cover in the original tutorial.

### CODE REVIEW

**Review by garlick — COMMENTED** [review]
Gave this a quick skim and LGTM.  These docs are excellent IMHO.

While reading through, I did note a couple of things that might need tweaking
- in the table of contents, section 2 refers to "launching and tracking job steps"  but the actual title of the page is "...tracking flux jobs" (more appropriate)
- that page begins with a paragraph about job IDs which implies that the reason for FLUIDs is to ensure IDs are unique across a hierarchy of Flux jobs/instances.  It  only ensures uniqueness within an instance, but does so without requiring a central allocator which improves the scalability of job submission within the instance.  In that way it is like a UUID except _L_ ocal not _U_ niversal.

**Comment by ryanday36** [comment]
Thanks for the feedback and correct explanation of FLUIDs @garlick! Can you take another look and make sure I incorporated it well.

**Comment by garlick** [comment]
It still kind of implies that the ids are unique across a  flux hierarchy, or at least that's the way I'm still reading it.  They are not unique though, you could have the same job ID in a parent instance and a child, or in siblings.  The design was all about generating unique IDs within an instance without having to bottleneck through a central allocator in the instance.

**Comment by ryanday36** [comment]
That's fair. I'm thinking I should just remove the sentences about Flux being hierarchical from that paragraph and change 'effectively unique identifiers for each job' to 'unique identifiers for each job in an instance'.

**Comment by ryanday36** [comment]
Okay. I think this should be better. I still mention that a allocation in Flux is a Flux instance in order to tie the language in the first two paragraphs together, but I removed the bits about hierarchy and hopefully made it more clear that the FLUIDs are only unique within an instance. Part of me wants to go through the full tutorial and replace all instances of the word "allocation" after section 1 with "Flux instance", but I think that would make it harder on people who jump into the middle somewhere to figure out how to do a specific thing.

**Comment by garlick** [comment]
Looks great!

**Pull request merged**
